# [](fg:#ff9248 bg:#89d1dc)\
# $all\
format = """
[](#003543)\
$username\
$hostname\
[](fg:#003543 bg:#0087D8)\
$directory\
[](fg:#0087D8 bg:#ff9248)\
$git_branch\
$git_status\
$git_commit\
[](fg:#ff9248 bg:#33658A)\
$time\
[](fg:#33658A)\
$cmd_duration
$character"""
[username]
show_always = true
format = "[$user@](bg:#003543)"

[hostname]
format = "[$ssh_symbol$hostname ]($style)"
style = 'bg:#003543'
ssh_only = false

[directory]
format = "[ $path ]($style)[$read_only]($read_only_style)"
style = "bg:#0087D8 fg:#003544"
truncation_length = 10
# style = "red"


[time]
format = '[ $time ]($style)'
disabled = false
time_format = "%R"
style = "bg:#33658A"
 
 [git_branch]
symbol = ""
style = "bg:#ff9248 fg:#193549"
# style = "bold yellow"
format = '[ $symbol $branch ]($style)'

# ~/.config/starship.toml
[git_commit]
commit_hash_length = 8
style = "bold red"

[git_status]
style = "bg:#ff9248 fg:#193549"
format = '([\[$all_status$ahead_behind\]]($style))'

[character]
success_symbol = "[➜](bold green)"
# success_symbol = "[\\$](bold green)"
error_symbol = "[×](bold red)"
format = '$symbol '

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed green"


# right_format = """$time"""
